# Generated by Django 5.1.4 on 2025-05-19 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='sent_at',
        ),
    ]
